S01 us05 update praticians
WildCodeSchool/2023-03-JS-TLSE-P3-Serenity pull request #22
Opened 2023-06-23 14:14 UTC by jeannicaise

2023-06-23 14:44 UTC, MatthieuGuinet requested changes

2023-06-23 14:44 UTC, MatthieuGuinet commented on backend/src/models/AdministratorManager.js
Remettre ItemManager ou le supprimer

2023-06-23 14:44 UTC, MatthieuGuinet commented on backend/src/models/PracticianManager.js
Pratician ->Practician Pour le nom de la class et l'export

2023-06-23 14:44 UTC, MatthieuGuinet commented on backend/src/models/index.js
Remettre ItemManager ou supprimer

2023-06-23 14:44 UTC, MatthieuGuinet commented on frontend/src/components/PracticianListModal.jsx
Rassembler les useContext

2023-06-23 14:44 UTC, MatthieuGuinet commented on frontend/src/components/PracticianListModal.jsx
Les commentaires en anglais dans le code

2023-06-23 14:44 UTC, MatthieuGuinet commented on frontend/src/components/PracticianListModal.jsx
Mettre les modales dans de nouveaux composants

2023-06-23 14:44 UTC, MatthieuGuinet commented on frontend/src/styles/PracticianListModal.scss
changer bi par fi-rr ligne 45
enlever ligne 100

2023-06-26 07:42 UTC, Swadek approved these changes

2023-06-26 07:53 UTC, ArthurHtbk requested changes

2023-06-26 07:53 UTC, ArthurHtbk commented on backend/src/controllers/PraticianControllers.js
> +        res.send(rows[0]);
Attention, il manque le statut dans la réponse

2023-06-26 07:53 UTC, ArthurHtbk commented on backend/src/controllers/PraticianControllers.js
> +const AddPractician = (req, res) => {
Attention au nom de la fonction : cette fonction sert manifestement à mettre à jour des données, AddPratician n'est donc pas approprié.

2023-06-26 07:53 UTC, ArthurHtbk commented on backend/src/controllers/PraticianControllers.js
> +const updatePractician = (req, res) => {
Même remarque que plus haut : ici on ajoute des données dans la BDD, on ne les modifie pas, updatePratcican n'est donc pas un nom approprié.

2023-06-26 13:32 UTC, Swadek approved these changes

2023-06-26 13:48 UTC, ArthurHtbk approved these changes

2023-06-26 13:49 UTC, merged