S02 us07 form admin
WildCodeSchool/2023-03-JS-TLSE-P3-Serenity pull request #26
Opened 2023-06-27 10:31 UTC by Swadek

2023-06-27 10:36 UTC, MatthieuGuinet approved these changes
OK

2023-06-27 12:49 UTC, aimach requested changes

2023-06-27 12:49 UTC, aimach commented on backend/src/controllers/FormControllers.js
> +    .insert({
remplacer req.body

2023-06-27 12:49 UTC, aimach commented on frontend/src/components/FormListModal.jsx
> +  useEffect(() => {
tout reprendre

2023-06-27 13:27 UTC, MatthieuGuinet approved these changes
Ok

2023-06-30 07:14 UTC, aimach approved these changes

2023-06-30 07:14 UTC, merged